### PR TITLE
Fixed installation order to eliminate compilation error warning

### LINKED ISSUE #657: A warning when installing v3.1.1
Hello,

There is one warning when we installing utPLSQL v 3.1.1. Could you fix it please? 

Greate thanks.

[14:06:18][Step 2/2] --------------------------------------------------------------
[14:06:18][Step 2/2] Installing component UT_COMPOUND_DATA_HELPER
[14:06:18][Step 2/2] 
[14:06:18][Step 2/2] Предупреждение: Пакет создан с ошибками компиляции. (Warning: The package was created with compilation errors)

### PR DESCRIPTION
**Pull request by Pazus**
Fixed installation order to eliminate compilation error warning
Removed ampersand symbol as some IDEs (PLSQL Developer) recognize it as a parameter to be defined
Removed unnecessary drop as ut_event_listener is already several lines before
Fixes #657

### CODE REVIEW

File: source/install.sql [hunk 1]
```diff
@@ -29,6 +29,7 @@ whenever oserror exit failure rollback
 prompt Switching current schema to &&ut3_owner
 prompt &&line_separator
 alter session set current_schema = &&ut3_owner;
+alter session set PLSQL_WARNINGS='ENABLE:ALL';
```
Comment (jgebal) [inline source/install.sql]: Warnings are enabled as part of development install. They were removed from the main install on purpose so users don't get worried that something is wrong.

**Comment by Mikhail5544** [comment]
Great thanks!

This fix will be in master branch with release v3.1.2?

**Comment by jgebal** [comment]
It will be included in next release
